SUPABASE_URL = "https://ytcumffxiktjkgfmmnis.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl0Y3VtZmZ4aWt0amtnZm1tbmlzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE5OTU5MjEsImV4cCI6MjA3NzU3MTkyMX0.eUbAOgHQlwJF5zDB8iSLgVV8T9MUolwNoWgVb7Ym8zE"
```